### ISSUE TITLE
PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND

### ISSUE THREAD

**Issue by mhwasil** [industrial-robotics/atwork_refbox_comm#1]
There is one error when I catkin make this package,
I followed this step before running catkin_make:
cd atwork_refbox_comm
git submodule init
git submodule update

and I received some objects.
```
####
#### Running command: "make -j8 -l8" in "/home/robocup/ros/kinetic/atwork-ref-box/build"
####
make[2]: *** No rule to make target '/home/robocup/ros/kinetic/atwork-ref-box/src/atwork_refbox_comm/atwork_pb_msgs/PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND', needed by 'atwork_refbox_comm/atwork_pb_msgs/VersionInfo.pb.cc'.  Stop.
CMakeFiles/Makefile2:447: recipe for target 'atwork_refbox_comm/atwork_pb_msgs/CMakeFiles/atwork_pb_msgs.dir/all' failed
make[1]: *** [atwork_refbox_comm/atwork_pb_msgs/CMakeFiles/atwork_pb_msgs.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target _atwork_ros_msgs_generate_messages_check_deps_BenchmarkState
Scanning dependencies of target _atwork_ros_msgs_generate_messages_check_deps_RobotStatusReport
Scanning dependencies of target _atwork_ros_msgs_generate_messages_check_deps_NavigationTask
Scanning dependencies of target _atwork_ros_msgs_generate_messages_check_deps_TriggeredConveyorBeltCommand
Scanning dependencies of target protobuf_comm_copy_headers
Scanning dependencies of target protobuf_comm
Scanning dependencies of target copy
make[2]: *** No rule to make target '/home/robocup/ros/kinetic/atwork-ref-box/src/atwork_refbox_comm/atwork_pb_msgs/PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND', needed by 'atwork_refbox_comm/atwork_pb_msgs/TransportationTask.pb.cc'.  Stop.
CMakeFiles/Makefile2:484: recipe for target 'atwork_refbox_comm/atwork_pb_msgs/CMakeFiles/copy.dir/all' failed
make[1]: *** [atwork_refbox_comm/atwork_pb_msgs/CMakeFiles/copy.dir/all] Error 2
```

**Comment by abhishekpadalkar** [comment]
`$ catkin_make
Base path: /home/robocup/ros/kinetic/atwork_refbox_comm
Source space: /home/robocup/ros/kinetic/atwork_refbox_comm/src
Build space: /home/robocup/ros/kinetic/atwork_refbox_comm/build
Devel space: /home/robocup/ros/kinetic/atwork_refbox_comm/devel
Install space: /home/robocup/ros/kinetic/atwork_refbox_comm/install
Creating symlink "/home/robocup/ros/kinetic/atwork_refbox_comm/src/CMakeLists.txt" pointing to "/opt/ros/kinetic/share/catkin/cmake/toplevel.cmake"
####
#### Running command: "cmake /home/robocup/ros/kinetic/atwork_refbox_comm/src -DCATKIN_DEVEL_PREFIX=/home/robocup/ros/kinetic/atwork_refbox_comm/devel -DCMAKE_INSTALL_PREFIX=/home/robocup/ros/kinetic/atwork_refbox_comm/install -G Unix Makefiles" in "/home/robocup/ros/kinetic/atwork_refbox_comm/build"
####
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/robocup/ros/kinetic/atwork_refbox_comm/devel
-- Using CMAKE_PREFIX_PATH: /home/robocup/ros/kinetic/atwork-ref-box/devel;/home/robocup/ros/kinetic/robocup/devel;/opt/ros/kinetic
-- This workspace overlays: /home/robocup/ros/kinetic/robocup/devel;/opt/ros/kinetic
-- Found PythonInterp: /usr/bin/python (found version "2.7.12") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/robocup/ros/kinetic/atwork_refbox_comm/build/test_results
-- Found gmock sources under '/usr/src/gmock': gmock will be built
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found gtest sources under '/usr/src/gmock': gtests will be built
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.14
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 4 packages in topological order:
-- ~~  - atwork_pb_msgs
-- ~~  - atwork_refbox_comm (metapackage)
-- ~~  - protobuf_comm
-- ~~  - atwork_ros_msgs
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'atwork_pb_msgs'
-- ==> add_subdirectory(atwork_refbox_comm/atwork_pb_msgs)
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so  
-- protobuf msgs directory exists
-- +++ processing catkin metapackage: 'atwork_refbox_comm'
-- ==> add_subdirectory(atwork_refbox_comm/atwork_refbox_comm)
-- +++ processing catkin package: 'protobuf_comm'
-- ==> add_subdirectory(atwork_refbox_comm/protobuf_comm)
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   thread
--   system
--   chrono
--   date_time
--   atomic
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- protobuf_comm source directory found.
-- +++ processing catkin package: 'atwork_ros_msgs'
-- ==> add_subdirectory(atwork_refbox_comm/atwork_ros_msgs)
-- Disabling the following message generators: genlisp
-- Using these message generators: gencpp;geneus;gennodejs;genpy
-- atwork_ros_msgs: 18 messages, 0 services
-- Configuring done
-- Generating done
-- Build files have been written to: /home/robocup/ros/kinetic/atwork_refbox_comm/build
####
#### Running command: "make -j8 -l8" in "/home/robocup/ros/kinetic/atwork_refbox_comm/build"
####
make[2]: *** No rule to make target '/home/robocup/ros/kinetic/atwork_refbox_comm/src/atwork_refbox_comm/atwork_pb_msgs/PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND', needed by 'atwork_refbox_comm/atwork_pb_msgs/VersionInfo.pb.cc'.  Stop.
CMakeFiles/Makefile2:447: recipe for target 'atwork_refbox_comm/atwork_pb_msgs/CMakeFiles/atwork_pb_msgs.dir/all' failed
make[1]: *** [atwork_refbox_comm/atwork_pb_msgs/CMakeFiles/atwork_pb_msgs.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
Scanning dependencies of target _atwork_ros_msgs_generate_messages_check_deps_TaskInfo
Scanning dependencies of target _atwork_ros_msgs_generate_messages_check_deps_BenchmarkFeedback
Scanning dependencies of target protobuf_comm_copy_headers
Scanning dependencies of target _atwork_ros_msgs_generate_messages_check_deps_Item
Scanning dependencies of target protobuf_comm
Scanning dependencies of target copy
Scanning dependencies of target _atwork_ros_msgs_generate_messages_check_deps_TriggeredConveyorBeltCommand
make[2]: *** No rule to make target '/home/robocup/ros/kinetic/atwork_refbox_comm/src/atwork_refbox_comm/atwork_pb_msgs/PROTOBUF_PROTOC_EXECUTABLE-NOTFOUND', needed by 'atwork_refbox_comm/atwork_pb_msgs/TransportationTask.pb.cc'.  Stop.
CMakeFiles/Makefile2:484: recipe for target 'atwork_refbox_comm/atwork_pb_msgs/CMakeFiles/copy.dir/all' failed
make[1]: *** [atwork_refbox_comm/atwork_pb_msgs/CMakeFiles/copy.dir/all] Error 2
[  1%] Building CXX object atwork_refbox_comm/protobuf_comm/CMakeFiles/protobuf_comm.dir/__/atwork_refbox/src/libs/protobuf_comm/server.cpp.o
[  2%] Building CXX object atwork_refbox_comm/protobuf_comm/CMakeFiles/protobuf_comm.dir/__/atwork_refbox/src/libs/protobuf_comm/peer.cpp.o
[  2%] Building CXX object atwork_refbox_comm/protobuf_comm/CMakeFiles/protobuf_comm.dir/__/atwork_refbox/src/libs/protobuf_comm/message_register.cpp.o
[  2%] Built target _atwork_ros_msgs_generate_messages_check_deps_TaskInfo
[  2%] Built target _atwork_ros_msgs_generate_messages_check_deps_BenchmarkFeedback
[  2%] Built target _atwork_ros_msgs_generate_messages_check_deps_Item
[  3%] Building CXX object atwork_refbox_comm/protobuf_comm/CMakeFiles/protobuf_comm.dir/__/atwork_refbox/src/libs/protobuf_comm/client.cpp.o
[  3%] Built target _atwork_ros_msgs_generate_messages_check_deps_TriggeredConveyorBeltCommand
[  4%] Building CXX object atwork_refbox_comm/protobuf_comm/CMakeFiles/protobuf_comm.dir/__/atwork_refbox/src/libs/protobuf_comm/crypto.cpp.o
[  4%] Built target protobuf_comm_copy_headers
[  5%] Linking CXX shared library /home/robocup/ros/kinetic/atwork_refbox_comm/devel/lib/libprotobuf_comm.so
[  5%] Built target protobuf_comm
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j8 -l8" failed
`

**Comment by abhishekpadalkar** [comment]
Fixed it by installing `protobuf-compiler` . 
`sudo apt install protobuf-compiler`
